services:
  postgres-main:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-main:/var/lib/postgresql/data
  postgres-audit:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_AUDIT_DB}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-audit:/var/lib/postgresql/data

volumes:
  pgdata-main:
  pgdata-audit: